# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 01:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('visible_in_menus', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=120)),
                ('links', models.ManyToManyField(blank=True, to='elemental.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('visible_to_public', models.BooleanField(default=False)),
                ('visible_in_menus', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='pages',
            field=models.ManyToManyField(blank=True, to='elemental.Page'),
        ),
    ]
